const EMPTY=0;const FIRST=1;const SECOND=2;const PLAYER_NAME=["","青","赤"];
const boardElement=document.getElementById("board");const sizeInput=document.getElementById("sizeInput");const newGameButton=document.getElementById("newGameButton");const undoButton=document.getElementById("undoButton");const randomButton=document.getElementById("randomButton");const autoButton=document.getElementById("autoButton");const clearButton=document.getElementById("clearButton");const fullBoardSecondWinsInput=document.getElementById("fullBoardSecondWinsInput");const firstCannotCenterInput=document.getElementById("firstCannotCenterInput");const turnText=document.getElementById("turnText");const legalText=document.getElementById("legalText");const resultText=document.getElementById("resultText");const firstCount=document.getElementById("firstCount");const secondCount=document.getElementById("secondCount");const emptyCount=document.getElementById("emptyCount");const historyList=document.getElementById("historyList");const activeRulesText=document.getElementById("activeRulesText");const theoryText=document.getElementById("theoryText");
let n=5;let board=[];let currentPlayer=FIRST;let history=[];let gameOver=false;let winnerPlayer=null;let gameOverReason="";let autoTimer=null;
function createEmptyBoard(size){return Array.from({length:size},()=>Array(size).fill(EMPTY));}
function opponent(player){return player===FIRST?SECOND:FIRST;}
function inBoard(row,col){return row>=0&&row<n&&col>=0&&col<n;}
function isOddBoard(){return n%2===1;}
function isCenterCell(row,col){if(!isOddBoard())return false;const center=Math.floor(n/2);return row===center&&col===center;}
function isForbiddenByAdditionalRule(row,col,player){return firstCannotCenterInput.checked&&player===FIRST&&history.length===0&&isCenterCell(row,col);}
function nearestStoneInDirection(row,col,dr,dc){let r=row+dr;let c=col+dc;while(inBoard(r,c)){if(board[r][c]!==EMPTY)return board[r][c];r+=dr;c+=dc;}return EMPTY;}
function isLegalMove(row,col,player){if(!inBoard(row,col))return false;if(board[row][col]!==EMPTY)return false;if(isForbiddenByAdditionalRule(row,col,player))return false;const directions=[[-1,0],[1,0],[0,-1],[0,1]];for(const [dr,dc] of directions){const nearest=nearestStoneInDirection(row,col,dr,dc);if(nearest===player)return false;}return true;}
function getLegalMoves(player){const moves=[];for(let row=0;row<n;row++){for(let col=0;col<n;col++){if(isLegalMove(row,col,player))moves.push({row,col});}}return moves;}
function moveToLabel(row,col){return "("+(row+1)+", "+(col+1)+")";}
function cloneBoard(source){return source.map(row=>row.slice());}
function placeStone(row,col){if(gameOver)return;if(!isLegalMove(row,col,currentPlayer))return;board[row][col]=currentPlayer;history.push({player:currentPlayer,row,col,board:cloneBoard(board)});currentPlayer=opponent(currentPlayer);updateGameState();render();}
function undoMove(){stopAutoPlay();if(history.length===0)return;history.pop();if(history.length===0){board=createEmptyBoard(n);currentPlayer=FIRST;}else{const last=history[history.length-1];board=cloneBoard(last.board);currentPlayer=opponent(last.player);}gameOver=false;winnerPlayer=null;gameOverReason="";updateGameState();render();}
function randomMove(){if(gameOver)return;const legalMoves=getLegalMoves(currentPlayer);if(legalMoves.length===0){updateGameState();render();return;}const selected=legalMoves[Math.floor(Math.random()*legalMoves.length)];placeStone(selected.row,selected.col);}
function startAutoPlay(){if(autoTimer!==null){stopAutoPlay();return;}autoButton.textContent="自動プレイ停止";autoTimer=setInterval(()=>{if(gameOver){stopAutoPlay();return;}randomMove();},350);}
function stopAutoPlay(){if(autoTimer!==null){clearInterval(autoTimer);autoTimer=null;}autoButton.textContent="自動プレイ開始";}
function countCells(){let first=0,second=0,empty=0;for(let row=0;row<n;row++){for(let col=0;col<n;col++){if(board[row][col]===FIRST)first++;else if(board[row][col]===SECOND)second++;else empty++;}}return{first,second,empty};}
function updateGameState(){const counts=countCells();const legalMoves=getLegalMoves(currentPlayer);gameOver=false;winnerPlayer=null;gameOverReason="";if(counts.empty===0&&fullBoardSecondWinsInput.checked){gameOver=true;winnerPlayer=SECOND;gameOverReason="盤面がすべて埋まったため、追加ルールにより赤の勝ちです。";return;}if(legalMoves.length===0){gameOver=true;winnerPlayer=opponent(currentPlayer);gameOverReason=PLAYER_NAME[currentPlayer]+"は合法手がありません。";}}
function calculateCellSize(){if(n<=5)return 64;if(n<=8)return 54;if(n<=12)return 42;if(n<=18)return 32;return 24;}
function getActiveRulesText(){const rules=[];if(fullBoardSecondWinsInput.checked)rules.push("すべて埋まったら赤の勝ち");if(firstCannotCenterInput.checked)rules.push("青は初手で中央には置けない"+(isOddBoard()?"":"（偶数盤面なので中央1マスは存在しません）"));return rules.length===0?"追加ルール：なし":"追加ルール："+rules.join(" / ");}
function getTheoreticalText(){if(fullBoardSecondWinsInput.checked||firstCannotCenterInput.checked)return "もう何もわからない";if(n%2===0)return "基本ルールの理論予想：n が偶数だと、赤が180度回転対称戦略により必勝です。";return "基本ルールの理論予想：n が奇数だと，初手中央における先手が有利かもしれないが，結果はわからない．";}
function renderBoard(){const legalMoves=getLegalMoves(currentPlayer);const legalKeySet=new Set(legalMoves.map(move=>move.row+","+move.col));const lastMove=history.length>0?history[history.length-1]:null;boardElement.innerHTML="";boardElement.style.gridTemplateColumns="repeat("+n+", var(--cell-size))";boardElement.style.setProperty("--cell-size",calculateCellSize()+"px");for(let row=0;row<n;row++){for(let col=0;col<n;col++){const cell=document.createElement("button");cell.className="cell";cell.type="button";cell.textContent="";cell.title=moveToLabel(row,col);if(board[row][col]===FIRST){cell.classList.add("first");}else if(board[row][col]===SECOND){cell.classList.add("second");}else if(!gameOver&&legalKeySet.has(row+","+col)){cell.classList.add("legal");}else if(!gameOver&&isForbiddenByAdditionalRule(row,col,currentPlayer)){cell.classList.add("forbidden");cell.title=moveToLabel(row,col)+"：追加ルールにより初手は禁止";}else if(board[row][col]===EMPTY){cell.classList.add("illegal-empty");}if(lastMove!==null&&lastMove.row===row&&lastMove.col===col)cell.classList.add("last");cell.addEventListener("click",()=>placeStone(row,col));boardElement.appendChild(cell);}}}
function renderStatus(){const legalMoves=getLegalMoves(currentPlayer);const counts=countCells();firstCount.textContent=counts.first;secondCount.textContent=counts.second;emptyCount.textContent=counts.empty;activeRulesText.textContent=getActiveRulesText();theoryText.textContent=getTheoreticalText();turnText.className="turn";resultText.className="";if(currentPlayer===FIRST)turnText.classList.add("first");else turnText.classList.add("second");if(gameOver){turnText.textContent="ゲーム終了";legalText.textContent=gameOverReason;resultText.textContent=PLAYER_NAME[winnerPlayer]+"の勝ちです。";resultText.className="winner";}else{turnText.textContent=PLAYER_NAME[currentPlayer]+"の手番";legalText.textContent="合法手："+legalMoves.length+" 個";resultText.textContent="";}undoButton.disabled=history.length===0;randomButton.disabled=gameOver;}
function renderHistory(){historyList.innerHTML="";if(history.length===0){const li=document.createElement("li");li.textContent="まだ着手はありません。";historyList.appendChild(li);return;}for(let i=0;i<history.length;i++){const move=history[i];const li=document.createElement("li");li.textContent=(i+1)+". "+PLAYER_NAME[move.player]+" → "+moveToLabel(move.row,move.col);historyList.appendChild(li);}historyList.scrollTop=historyList.scrollHeight;}
function render(){renderBoard();renderStatus();renderHistory();}
function newGame(){stopAutoPlay();const inputValue=Number(sizeInput.value);if(!Number.isInteger(inputValue)||inputValue<1||inputValue>30){alert("盤面サイズ n は 1 以上 30 以下の整数にしてください。");sizeInput.value=String(n);return;}n=inputValue;board=createEmptyBoard(n);currentPlayer=FIRST;history=[];gameOver=false;winnerPlayer=null;gameOverReason="";updateGameState();render();}
function resetBoardOnly(){stopAutoPlay();board=createEmptyBoard(n);currentPlayer=FIRST;history=[];gameOver=false;winnerPlayer=null;gameOverReason="";updateGameState();render();}
function handleRuleToggle(){stopAutoPlay();updateGameState();render();}
newGameButton.addEventListener("click",newGame);clearButton.addEventListener("click",resetBoardOnly);undoButton.addEventListener("click",undoMove);randomButton.addEventListener("click",randomMove);autoButton.addEventListener("click",startAutoPlay);fullBoardSecondWinsInput.addEventListener("change",handleRuleToggle);firstCannotCenterInput.addEventListener("change",handleRuleToggle);sizeInput.addEventListener("keydown",event=>{if(event.key==="Enter")newGame();});newGame();
